### ISSUE TITLE
kotlin target version is 1.6.21

### ISSUE THREAD

**Issue by weijunfeng** [rickclephas/KMM-ViewModel#12]
At present, my project supports up to Kotlin 1.6.21 version. Due to the upgrade of Kotlin version, it has a great impact on the project. Can you provide a version of Kotlin 1.6.21?

**Comment by rickclephas** [comment]
Sure, I will take a look at this later this week.

**Comment by rickclephas** [comment]
FYI version `1.0.0-ALPHA-3-kotlin-1.6.21` should be available in a couple hours from Maven Central.
