### ISSUE TITLE
Only the first state is published with @StateViewModel

### ISSUE THREAD

**Issue by xxfast** [rickclephas/KMM-ViewModel#18]
Hi.

I've been following @joreilly's Confetti [sample](https://github.com/joreilly/Confetti/blob/main/iosApp/iosApp/ContentView.swift) and I have my shared view model defined like 
```kotlin
class MyViewModel() : KMMViewModel() {
  val states: StateFlow<Int> = flow {
      var count = 1
      while (true) {
        delay(1000)
        println("EMITTING $count")
        emit(count++)
      }
    }
    .stateIn(this, SharingStarted.Eagerly, 0)
}

@NativeCoroutinesState
val MyViewModel.state: StateFlow<MainState> get() = states
```

This is consumed on the swift side like
```swift
import SwiftUI
import Combine
import KMMViewModelCore
import KMMViewModelSwiftUI
import KMPNativeCoroutinesCore

struct MyScreen: View {
  @StateViewModel private var viewModel = .init()  
  var body: some View {
    MyView(viewModel: $viewModel)
  }
}

struct MyView: MyView {
  @ObservedViewModel var viewModel: MyViewModel
  
  init(viewModel: ObservableViewModel<MyViewModel>.Projection) {
    self._viewModel = ObservedViewModel(viewModel)
  }
  
  var body: some View {
    let _ = print("STATE CONSUMED", viewModel.state)
  }
}
```
 
 From the logger, it looks like only the first-ever state is consumed even though subsequent states are emitted 
 ```log
STATE CONSUMED 0
EMITTING 1
EMITTING 2
EMITTING 3
EMITTING 4
EMITTING 5
 ```
 
 Is this the intended way to use `@StateViewModel`/`@ObservedViewModel`? Not sure if I'm missing something here.

**Comment by xxfast** [comment]
Looks like i was missing the magic that was mentioned [here](https://github.com/rickclephas/KMM-ViewModel/issues/6)

I needed to use a special overridden `stateIn` to make this work as expected. Perhaps this needs to be documented so that it won't be easily missed 😄 

Anyways - feel free to close this issue or use it to document this

**Comment by rickclephas** [comment]
FYI I have updated the README to more clearly indicate the requirements around the `stateIn` and `MutableStateFlow` functions.
