### ISSUE TITLE
Publish to maven central?

### ISSUE THREAD

**Issue by Reedyuk** [rickclephas/KMM-ViewModel#2]
Hi @rickclephas - any chance you can publish this to sonatype under as an open source project?

You can use github workflows for free to build and push it to sonatype.

Here is one of my KMM open source projects as an example
https://github.com/Reedyuk/blue-falcon

Thanks

**Comment by rickclephas** [comment]
Hey @Reedyuk , definitely! I have been a bit busy, but I will publish the initial release later this week 😁.

**Comment by rickclephas** [comment]
Initial releases for Kotlin 1.7.21 and 1.8.0-RC have been published to Maven Central 🚀.
