### ISSUE TITLE
Question: Build Error

### ISSUE THREAD

**Issue by walter-whytied** [rickclephas/KMM-ViewModel#25]
~~Hi Rick. I'm trying to use Kmm-ViewModel in my project. I am getting the following error. Any idea how I can resolve this?~~

```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.rickclephas.kmm.viewmodel.KMMViewModel, unresolved supertypes: androidx.lifecycle.ViewModel
Adding -Xextended-compiler-checks argument might provide additional information.
```

Edited:

I figured it out. I was missing viewmodel dependency in the android module.

**Comment by pabloski0000** [comment]
Hi, I've read the READ.ME and in principle added all the dependencies. Still, I'm getting the same error as you. Probably, I'm doing something wrong. Could you provide how your dependencies look like. Thank you

**Comment by walter-whytied** [comment]
@pabloski0000 This is how my build.gradle file looks like:

```  DSL

sourceSets {
         sourceSets["androidMain"].dependencies {
            implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1")
        }

        sourceSets["commonMain"].dependencies {
            implementation("com.rickclephas.kmm:kmm-viewmodel-core:1.0.0-ALPHA-8")
        }
}
```

Let me know if this helps.

**Comment by pabloski0000** [comment]
Yes, it worked. I was missing the first library. Thank you very much.
