### ISSUE TITLE
On iOS state is not updating the views.

### ISSUE THREAD

**Issue by oianmol** [rickclephas/KMM-ViewModel#30]
Hi! Thanks for creating KMMViewModel! 🙇🏼 

I have started using KMMViewModel like this, also I have setup the extension for `Kmm_viewmodel_coreKMMViewModel` like mentioned in the docs.

```
class LoginViewModel() : KMMViewModel() {
    @NativeCoroutinesState
    val uiState = MutableStateFlow(LoginUIState())
}
```

on iOS I was able to initialise the VM in my View

```
struct LoginScreen: View {
    @ObservedViewModel var viewModel : LoginViewModel

    init() {
        self.viewModel = LoginViewModel()
    }

    var body: some View {
          viewModel.uiState // this never updates
      }
}
```

The problem is that the `uiState` never updates even if the ViewModel emits new values to the state flow , am i doing something wrong here ?

**Comment by rickclephas** [comment]
Hi! The only thing missing is the KMM-ViewModel constructor for `MutableStateFlow`:
```diff
- val uiState = MutableStateFlow(LoginUIState())
+ val uiState = MutableStateFlow(viewModelScope, LoginUIState())
```

That should make sure to propagate state changes to iOS.

**Comment by oianmol** [comment]
> Hi! The only thing missing is the KMM-ViewModel constructor for `MutableStateFlow`:
> 
> ```diff
> - val uiState = MutableStateFlow(LoginUIState())
> + val uiState = MutableStateFlow(viewModelScope, LoginUIState())
> ```
> 
> That should make sure to propagate state changes to iOS.



Do you mean something like this ? because MutableStateFlow doesn't accept the scope in the constructor ?

```
    @NativeCoroutinesState
    val _uiState = MutableStateFlow(LoginUIState())

    @NativeCoroutinesState
    val uiState: StateFlow<LoginUIState> =
        _uiState.asStateFlow()
            .stateIn(viewModelScope, SharingStarted.WhileSubscribed(), LoginUIState())
```

This also didn't work sadly! Do you have any example which actually works ?

**Comment by oianmol** [comment]
Ohhh! The MutableStateFlow that you have created ! `com.rickclephas.kmm.viewmodel.MutableStateFlow` ! Please rename it to something like RickMutableStateFlow 😛  I couldn't have guessed that 😆
