### ISSUE TITLE
add support for KSP

### ISSUE THREAD

**Issue by ldobransky** [rickclephas/KMM-ViewModel#32]
Hello I have in viewmodel variables like 
`private val _loginState = MutableStateFlow<LoginStatus>(viewModelScope, LoginStatus.NonAuthenticated)
    @NativeCoroutinesState
    val loginState = _loginState.asStateFlow()`

but in iOS when I have created viewmodel I can't have access to this variable, functions are visible, calling that functions is working well.
Can somebody help me where I have issue?
<img width="415" alt="image" src="https://github.com/rickclephas/KMM-ViewModel/assets/57485826/65945f52-488d-482d-8af4-21641169872f">

**Comment by rickclephas** [comment]
Hi! A couple questions to better understand your project:
- Is the KSP plugin applied to your Kotlin module?
- Is the `LoginViewModel` part of the `shared` Kotlin module, or is it part of another Kotlin module?
- How is the `viewModel` property defined in Swift?

**Comment by ldobransky** [comment]
1. yes in shared build.kts.gradle id("com.google.devtools.ksp") version "1.8.21-1.0.11"
2. yes it's in shared module
3.
I have class
`class LoginViewModel: shared.LoginViewModel {
}`
and then in view
`@StateViewModel var viewModel = LoginViewModel()`

**Comment by rickclephas** [comment]
Alright that looks good. Is this an open-source project, or could you share a reproduction project?

**Comment by ldobransky** [comment]
I found new info, there is conflict with moko resources library and ksp... so going try to solve this
`Some problems were found with the configuration of task ':shared:kspKotlinIosX64' (type 'KspTaskNative').
  - Gradle detected a problem with the following location: '/Users/lukas.dobransky/Documents/Projects/game-tracker/shared/build/generated/moko/iosX64Main/src'.
    
    Reason: Task ':shared:kspKotlinIosX64' uses this output of task ':shared:generateMRiosX64Main' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':shared:generateMRiosX64Main' as an input of ':shared:kspKotlinIosX64'.
      2. Declare an explicit dependency on ':shared:generateMRiosX64Main' from ':shared:kspKotlinIosX64' using Task#dependsOn.
      3. Declare an explicit dependency on ':shared:generateMRiosX64Main' from ':shared:kspKotlinIosX64' using Task#mustRunAfter.
    `

**Comment by rickclephas** [comment]
Alright, I am unsure if that is related to the issue, but please do let me know if you have more details on how to reproduce the issue.

**Comment by ldobransky** [comment]
I think we should rename the ticket to something like add support with moko resources library, because when I want to use this library and moko resources there is a conflict what I sent above. When I removed moko from project, kmm-viewmodels start working. So I can edit the title of the issue

**Comment by ldobransky** [comment]
I fixed the issue with that code, for another cpu types is need to add the same code: but it fixed the issue, maybe you can update readme, when somebody has issue with ksp, here is the solution:
`afterEvaluate {
    tasks {
        val generateMRiosX64Main by getting
        val kspKotlinIosX64 by getting
        kspKotlinIosX64.dependsOn(generateMRiosX64Main)
    }
}`

**Comment by rickclephas** [comment]
Thanks for the update! 
Actually KMP-NativeCoroutines uses KSP, as far as I can tell moko-resources doesn't use KSP.
Anyway looking at your fix the issues seems to be with moko-resources and KSP.
Might be worth it to create an issue for moko-resources.
