### ISSUE TITLE
Cannot inherit from non-open class outside of its defining module

### ISSUE THREAD

**Issue by humblehacker** [rickclephas/KMM-ViewModel#36]
The readme claims that it's possible to subclass my view model in Swift:

```swift 
class TimeTravelViewModel: shared.TimeTravelViewModel {
```

... but when I try I get the error _Cannot inherit from non-open class 'MyViewModel' outside of its defining module_. Any advice?

**Comment by rickclephas** [comment]
Hi! In order to subclass the ViewModel in Swift you'll need to mark the Kotlin VM as `open`:
```kotlin
open class TimeTravelViewModel: KMMViewModel()
```

**Comment by humblehacker** [comment]
🤦 Calling Kotlin from Swift has muddied my brain! Thanks and sorry for the noise.
