### ISSUE TITLE
Android target includes a BuildConfig class

### ISSUE THREAD

**Issue by chrisbanes** [rickclephas/KMM-ViewModel#42]
Just letting you know that the Android includes the generated `BuildConfig` class. Libraries should avoid exporting these as they can easily clash with in application projects.

You can disable it globally by setting `android.defaults.buildfeatures.buildconfig = false` in your `gradle.properties`

**Comment by rickclephas** [comment]
Thanks again for the PR, it has been released in [v1.0.0-ALPHA-12](https://github.com/rickclephas/KMM-ViewModel/releases/tag/v1.0.0-ALPHA-12).
