### ISSUE TITLE
Publish Swift implementations to CocoaPods

### ISSUE THREAD

**Issue by xxfast** [rickclephas/KMM-ViewModel#5]
Similar to [KMP-NativeCoroutines](https://github.com/rickclephas/KMP-NativeCoroutines), is it possible to publish the swift implementations to Cocopods?

**Comment by rickclephas** [comment]
Yeah that shouldn't be an issue.
Would you mind sharing why you need CocoaPods instead of Swift Package Manager?

**Comment by rickclephas** [comment]
@xxfast I have added the `.podspec` files, the next release will also be published to CocoaPods trunk.
For now you should be able to use the library with CocoaPods via the Git URL.

**Comment by xxfast** [comment]
> Yeah that shouldn't be an issue.
> Would you mind sharing why you need CocoaPods instead of Swift Package Manager?

All my other iOS dependencies are from cocopods and wanting to keep all the dependencies in a package manager

**Comment by rickclephas** [comment]
FYI [v1.0.0-ALPHA-3](https://github.com/rickclephas/KMM-ViewModel/releases/tag/v1.0.0-ALPHA-3) has been published to CocoaPods.

**Comment by xxfast** [comment]
@rickclephas Can we also update the README with instructions for cocopods?

**Comment by rickclephas** [comment]
@xxfast sorry your comment got a little lost in my email. Just updated the README with some instructions for CocoaPods.
