### ISSUE TITLE
State update is reinitializing the entire screen in SwiftUI

### ISSUE THREAD

**Issue by smEvolutio** [rickclephas/KMM-ViewModel#51]
There's an issue when for example in shared part:

`init {
    viewModelScope.coroutineScope.launch {
        while (true) {
            delay(2000)
            _homeUiState.update { it.copy(error = if (it.error == null) "error" else null) }
        }
    }
}`

When in SwiftUI using this view model as: @EnvironmentViewModel private var homeViewModel: HomeViewModel

and if you implement in SwiftUI screen:

`init() {
        print("code 1 - init")
    }`

`.onChange(of: homeViewModel.homeUiState.error) { error in
            if error != nil {
                showAlert = true
            } else {
                showAlert = false
            }
        }`

The screen will always be reinitialized. You will always get code 1 - init after state change.

**Comment by rickclephas** [comment]
I believe this is to be expected and also the case for pure Swift `ObservableObject`s, right?

**Comment by rickclephas** [comment]
So how are you creating and storing the viewmodel when using `@EnvironmentViewModel`?
It sounds like some higher view is also observing the viewmodel, resulting in the calls to the `init`.

**Comment by rickclephas** [comment]
The following should be enough to use `environmentViewModel`:
```swift
struct MyApp: App {

    var homeViewModel: HomeViewModel = ViewModelsHelper().homeViewModel

    var body: some Scene {
        WindowGroup {
            HomeScreenView() .environmentViewModel(homeViewModel)
        }
    }
}
```
