### ISSUE TITLE
Module with the Main dispatcher is missing on desktop JVM

### ISSUE THREAD

**Issue by estivensh4** [rickclephas/KMM-ViewModel#53]
when i try to use any function of the shared viewmodel from the jvm(desktop) target i get this error, even though i added the coroutines as the log suggests i still get the same error

**Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core**

**Comment by rickclephas** [comment]
Are you by any chance using Compose Multiplatform? If that's the case then adding the following dependency should provide the Main dispatcher:
```kotlin
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.7.3")
```

**Comment by estivensh4** [comment]
> Are you by any chance using Compose Multiplatform? If that's the case then adding the following dependency should provide the Main dispatcher:
> 
> ```kotlin
> implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.7.3")
> ```

it worked perfectly, this should be added as an issue to add it in the library or it should be documented? so that other people do not have the same problem.

**Comment by rickclephas** [comment]
Great! I will make sure to update the README 👍🏻
