### ISSUE TITLE
Is the project upgradable to java 1.8?

### ISSUE THREAD

**Issue by karlozalb** [rickclephas/KMM-ViewModel#62]
I've seen comments in the kts files about this bug -> https://issuetracker.google.com/issues/260059413 is causing the project to be using java 11.

Is the java toolchain upgradable to 1.8 now? 

Thanks!

**Comment by rickclephas** [comment]
The workaround is there to make sure that the whole project is correctly specifying Java 11 compatibility.
Since AGP 8.1 this workaround is indeed no longer needed (so it wil be removed once AGP is updated).
However there aren't any plains to downgrade the compatibility to Java 8.
