### ISSUE TITLE
Ideal way of updating state from a suspending function

### ISSUE THREAD

**Issue by JonasHiltl** [rickclephas/KMM-ViewModel#7]
First off all, `KMM-Viewmodel` is great and even better in combination with `KMP-NativeCoroutines`, so thanks a lot for creating both.

I'm currently trying to update a `MutableStateFlow` inside a suspending function, but doing that gives me the following warning  since updates to the ui need to be done on the main thread:
```
[SwiftUI] Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
```

So here is my suspending function and how I call it:

```kotlin
class LoginViewModel : KMMViewModel() {
    @NativeCoroutinesState
    var loginLoading = MutableStateFlow(viewModelScope, false)
    
    suspend fun login() {
        loginLoading.update { true }
        val res = loginUseCase(email.value, password.value)
        res.fold(
            onSuccess = {
                appViewModel.dismissAuthFlow()
                appViewModel.setAccount(it)
            },
            onFailure = {
                appViewModel.setAccount(null)
            }
        )
        loginLoading.update { false }
    }
}
```
In SwiftUI I use a Task to run the async function:
```swift
Button(
    action: {
        Task {
            try await viewModel.login()
        }
    },
    label: {
        ZStack {
            if viewModel.loginLoading {
                ProgressView()
                    .colorInvert()
            } else {
                Text("Log in")
            }
        }
    }
)
```
I have experimented a bit on how to get it to work and wrapping all updates to the ui with `withContext(Dispatchers.Main)` does the trick. The working suspending function would look like this:
```kotlin
suspend fun login() {
    withContext(Dispatchers.Main) {
        loginLoading.update { true }
    }
    val res = loginUseCase(email.value, password.value)
    withContext(Dispatchers.Main) {
        res.fold(
            onSuccess = {
                appViewModel.dismissAuthFlow()
                appViewModel.setAccount(it)
            },
            onFailure = {
                appViewModel.setAccount(null)
            }
        )
        loginLoading.update { false }
    }
}
```
Is there a better way to update the ui from a suspending function than manually dispatching the updates on the main thread, to me it looks like this could be handled by the `MutableStateFlow` implementation for iOS.

**Comment by rickclephas** [comment]
Hey @JonasHiltl, thanks for the kind words and feedback!
I will make sure to fix this in KMM-ViewModel, should be easy enough to subscribe to the changes on the main thread.

**Comment by rickclephas** [comment]
I have reverted my initial fix, which only received the state change events on the main thread.
It didn't prevent you from updating the actual state on another thread, while this seems to work I started to wonder why this wasn't the default behaviour for SwiftUI. My best guess is that you actually need to update the state on the main thread (not just the change events).

The `stateIn` implementation already forces the updates to be on the main thread, so the only issue is when you "manually" try to update the state value.

I did some testing and have found that suspend functions started from ObjC/Swift aren't bound to a specific dispatcher.
```kotlin
suspend fun login() {
    loginLoading.update { true } // This runs on the main thread
    delay(1_000) // Using a delay to simulate a suspension, but could also be a network request, etc
    loginLoading.update { true } // This isn't guaranteed to run on the main thread
}
```

So at the moment I see 2 ways to force the dispatcher:
```kotlin
// 1. Wrap the login body in a withContext call
suspend fun login() = withContext(Dispatchers.Main) {
    // ...
}

// 2. launch a job in Kotlin instead of Swift
fun login() {
    viewModelScope.coroutineScope.launch {
        // ...
    }
}
```

This is an unfortunate limitation of the suspend function interoperability with ObjC/Swift.
However (at the moment) using [KMP-NativeCoroutines](https://github.com/rickclephas/KMP-NativeCoroutines) wouldn't fix this, as it's using the default dispatcher (by default).

I will make sure to update KMP-NativeCoroutines to use the `ViewModelScope` for `KMMViewModel`s.
Please track the following issue: https://github.com/rickclephas/KMP-NativeCoroutines/issues/86

**Comment by rickclephas** [comment]
FYI [v1.0.0-ALPHA-4](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-4) of KMP-NativeCoroutines adds support for KMM-ViewModel.
Using KMP-NativeCoroutines to call your suspend functions will guarantee that the function is run on the main thread, so there shouldn't be any more issues with the state being updated from a background thread.
